LineLength:
  Max: 100
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 40

Metrics/AbcSize:
  Enabled: false
